#!/usr/bin/perl
# Picker-thingy-gizmo0.0.1.>
#   Copyright (C) 2013  Matthew Blau

#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License along
#    with this program; if not, write to the Free Software Foundation, Inc.,
#    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

use warnings;
use strict;
our $files;
our $file;
our $random;
our $lastline;
our $url;
print "What file do you want to open? ", "\n";
### Lists txt files in current directory in a selectable numerical
### list.
 my @files = <*.txt>;
 my $x = 1;
 foreach $file (@files) {
    print $x." ".$file . "\n";
    $x++;
}
$file = <STDIN>; ## allows the user to choose what file
open FILE, "<$files[$file-1]" or die "Can not open $file: $!\n";
my @array=<FILE>; ## reads into an array
$lastline = '$array[array-1]';
do{
        $random = rand(@array);
        $url = $array[$random];
} while($url eq $lastline);
print $url;
open INFO, ">>$files[$file-1]" or die "Can not open $file: $!\n"; ##appends chosen object to end of file
my @array1=<INFO>;
print INFO "$url";
print @array1;
delete $array[$random];
push(@array, $url);
close FILE;
