#!/usr/bin/perl
# Picker-thingy-gizmo0.0.2.>
#   Copyright (C) 2013  Matthew Blau

#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License along
#    with this program; if not, write to the Free Software Foundation, Inc.,
#    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

#!/usr/bin/perl
#test_hash.plx
use warnings;
use strict;
my $choice;
my %hash =();
print "What file do you want to open? ", "\n";
my @files = <*.txt>;
my $x = 1;
 foreach $choice (@files) {
    print $x." ".$choice . "\n";
    $x++;
}

chomp ($choice = <>);
open FILE, "<$files[$choice-1]" or die "can not open $files[$choice]: $!\n";
my @urls = <FILE>;
my $lines = @urls;
my $num = 1;
foreach(@urls) {
	$hash{$num} = $_;
	$num++;
}
my $randomLine = int(rand($lines))+1;
print $hash{$randomLine};



